export const environment = {
  production: false,
  mode: 'prod',
  // api: 'https://orderna-api-dev-6znuanyvma-as.a.run.app/api/v1',
  api:'http://localhost:4000/api/v1',
  service: {
    auth: false,
    users: false,
    customer: false,
    transactions: false,
    stores: true,
    suppliers: false,
    products: true,
    discounts: false,
    userProfiles: false,
    printerSettings: false,
    subscriptionPlans: false,
    billingInvoices: false,
    invoices: false,
    feedbacks: false,
    inventory: true,
    purchases: true,
    revenues: false,
    zReports: false,
    averageOrderValues: false,
    dayOfWeekSales: false,
    timeOfDaySales: false,
    productSales: false,
    categorySales: false,
    tipsByDays: false,
    discountSummaries: false,
    discountedTransactions: false,
    refundedTransactions: false,
    failedTransactions: false,
    dailySummaries: false,
    allTransactions: false,
    cashRegisters: false,
    cashDrawers: false,
    sales: false,
    categories: true,
  }
};
